[tool.poetry]
name = "medical-ts-datasets"
version = "0.1.0"
description = ""
authors = ["Max Horn <max.horn@bsse.ethz.ch>"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
